apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 152096746892.dkr.ecr.ap-northeast-1.amazonaws.com/iac9270752/node-web-app:20220404
        ports:
        - containerPort: 80
